# Site settings
name: Kate Chen
title: Kate Chen | Entrepreneur, Adventurer, Engineer
description: Passionate about building consumer products with global impact
url: https://www.katezchen.com
baseurl: ''
email: kathleenzchen@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
social:
  - title: email
    url: mailto:kathleenzchen@gmail.com
  - title: instagram
    url: https://instagram.com/katezchen
  - title: github
    url: https://github.com/katzchen0713
  - title: linkedin
    url: https://www.linkedin.com/in/kathleenzchen

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
