- name: Roads Less Taken Podcast
  url: https://anchor.fm/katezchen
  description: Finding your path can be scary. Roads Less Taken is an initiative to explore all the jobs you dreamed about as a kid, but for some reason or another never pursued.

- name: Drone Video & Photography Archive
  url: https://www.instagram.com/afriendlydrone/
  description: Views from the sky bring a new perspective to a world I thought I knew. In this archive of drone videos and photography, I'm sharing the world through eyes in the sky.
